### ISSUE TITLE
Error connecting to main db, check main_index/.env file

### ISSUE THREAD

**Issue by a5868519** [bestinslot-xyz/OPI#12]
root@ip-172-26-5-209:~/OPI/modules# python3 restore.py
Will you index brc20 (y/n):y
Will you index bitmap (y/n):y
Will you index sns (y/n):y
Error connecting to main db, check main_index/.env file

DB_USER="postgres"
DB_HOST="localhost"
DB_PORT="5432"
DB_DATABASE="postgres"
DB_PASSWD=""
DB_SSL="true"
DB_MAX_CONNECTIONS=50
BITCOIN_CHAIN_FOLDER="/root/1"
BITCOIN_RPC_USER=""
BITCOIN_RPC_PASSWD=""
ORD_BINARY="./ord"
ORD_FOLDER="/root/OPI/ord/target/release/"
ORD_DATADIR="/root/1/ord"
NETWORK_TYPE="mainnet"

**Comment by Daniel212fsa** [comment]
please input DB_PASSWD=""

**Comment by nathanddrake** [comment]
Hey @a5868519, please reach out to #opi-support in our discord server for troubleshooting ✌️
https://discord.com/invite/g8FUhgb9Ts

**Comment by Alexzhuangyao** [comment]
check main_index/.env file

run  python3  main_index/reset_init.py   and  follow the input

you may forgot to input the DB_PASSWD
