### ISSUE TITLE
The latest hash I see on the opi dashboard is different from others. What is the general situation?

### ISSUE THREAD

**Issue by albertzzzzzzzzzzzz** [bestinslot-xyz/OPI#13]
The latest hash I see on the opi dashboard is different from others. What is the general situation?
Operator  test123

[pic](https://albert.4everland.store/1705920930.jpg)

**Comment by nathanddrake** [comment]
Hey @albertzzzzzzzzzzzz, please reach out to #opi-support in our discord server for troubleshooting ✌️
https://discord.com/invite/g8FUhgb9Ts
