### ISSUE TITLE
pbzip2: *ERROR: Could not write 903143 bytes to file [ret=-1]!  Aborting...

### ISSUE THREAD

**Issue by rainware** [bestinslot-xyz/OPI#15]
Downloading index.redb.tar.bz2
100.0%|█████████████████████████ | 8.35MB/s | source: s3://opi-backups/db_3/index_827115.redb.tar.bz2@
Extracting index.redb.tar.bz2 this may take a while (~30 mins)
pbzip2: *ERROR: Could not write 903143 bytes to file [ret=-1]!  Aborting...
pbzip2: *ERROR: system call failed with errno=[32: Broken pipe]!
pbzip2: *ERROR: system call failed with errno=[32: Broken pipe]!
Terminator thread: premature exit requested - quitting...
tar: Error opening archive: Child process exited with status 1
Error extracting index.redb

I met this error on macos

**Comment by nathanddrake** [comment]
Hey @rainware, please reach out to #opi-support in our discord server for troubleshooting ✌️
https://discord.com/invite/g8FUhgb9Ts

**Comment by rainware** [comment]
I have fixed this, the reason is I was using macos, and I have fixed by modifing the uncompress command to "pbzip2 -cd index.redb.tar.bz2| tar xv"

**Comment by rainware** [comment]
thx for your response, and sorry for my late response,

**Comment by rainware** [comment]
> Hey @rainware, please reach out to #opi-support in our discord server for troubleshooting ✌️ https://discord.com/invite/g8FUhgb9Ts

I have fixed this, the reason is I was using macos, and I have fixed by modifing the uncompress command to "pbzip2 -cd index.redb.tar.bz2| tar xv"
thx for your response, and sorry for my late response,
