### ISSUE TITLE
error: JSON-RPC error: transport error: unexpected HTTP code: 401

### ISSUE THREAD

**Issue by ioupeng** [bestinslot-xyz/OPI#24]
}
ord version: opi-ord 0.14.0-2

error: JSON-RPC error: transport error: unexpected HTTP code: 401
ERROR ON ORD!!!
Error: Command failed: ./ord --bitcoin-data-dir /var/lib/bitcoind/ --data-dir . --height-limit 831470  index run
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at main_index (/root/OPI/modules/main_index/index.js:159:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3097,
  stdout: null,
  stderr: null
}
How to solve this?

**Comment by nathanddrake** [comment]
@ioupeng Does this answer your question? Will close this issue in a few days ✌️

**Comment by ioupeng** [comment]
> @ioupeng Does this answer your question? Will close this issue in a few days ✌️

Solved it. Thank you so much, sir.
