### ISSUE TITLE
error: unrecognized subcommand 'Files\Bitcoin'

### ISSUE THREAD

**Issue by lfjigu** [bestinslot-xyz/OPI#26]
error: unrecognized subcommand 'Files\Bitcoin'

Usage: ord.exe [OPTIONS] <COMMAND>

For more information, try '--help'.
ERROR ON ORD!!!
Error: Command failed: ord.exe --bitcoin-data-dir C:\Program Files\Bitcoin --data-dir . --height-limit 768430  --bitcoin-rpc-user user --bitcoin-rpc-pass pass index run
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at main_index (C:\我的工作\OPI\modules\main_index\index.js:159:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 19680,
  stdout: null,
  stderr: null
}

**Comment by samedcildir** [comment]
I'll fix this issue with the next release 👍 
For now as a workaround, you can use a path without spaces, or you can modify line 150 on main.js to this:
`let ord_index_cmd = ord_binary + network_argument + " --bitcoin-data-dir \"" + chain_folder + "\" --data-dir \"" + ord_datadir + "\"" + cookie_arg + " --height-limit " + (ord_end_block_height) + " " + rpc_argument + " index run"`

**Comment by Dexta15** [comment]
Hello, did you find this response okay,
If so 
Would you like to close the issue, so that others who have the same issue can see that it has been answered...
Thank you

**Comment by lfjigu** [comment]
yes, it working now. thank you.

**Comment by Dexta15** [comment]
Glad to know that
