### ISSUE TITLE
Couldn't receive txs failed to fetch raw transaction: code -5 message No such mempool or blockchain transaction. Use gettransaction for wallet transactions. error: failed to get transaction for 

### ISSUE THREAD

**Issue by veryyoung** [bestinslot-xyz/OPI#29]
The main_index always reports an error and is stuck in the 767437 block. 

The error log is as follows.

[2024-03-02T06:23:59Z ERROR ord::index::updater] Couldn't receive txs failed to fetch raw transaction: code -5 message No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
error: failed to get transaction for 113a114c8bf57e8bc317591c458c0546a71805a3b536760f32abb26e68e21ff7

Txhash may be any one in this block.

I can use the bitcoin command line to find the correct raw transaction.

<img width="895" alt="image" src="https://github.com/bestinslot-xyz/OPI/assets/5799652/5febae5f-d10a-44bd-b916-9421e4b21a34">

My Bitcoin node has been fully synchronized and txindex is enabled. The following is my Bitcoin node configuration.
[main]
server=1
rpcuser=veryyoung
rpcpassword=
txindex=1

Can you help me solve this problem? Thanks

**Comment by veryyoung** [comment]
The getindexinfo command returns 
`{
  "txindex": {
    "synced": true,
    "best_block_height": 832891
  }
}`
synced is true, and the best_block_height is the current latest block height

**Comment by samedcildir** [comment]
This shouldn't happen if txindex is synced.
Can you make sure that you do not have another bitcoin node without txindex that ord is trying to connect to? Also, can you double check the network in main_index is set to mainnet?

**Comment by nathanddrake** [comment]
Hey @veryyoung does this solve the issue?

**Comment by veryyoung** [comment]
@samedcildir @nathanddrake 
Hi, thank you for your replies. My node data was downloaded from the Internet and may lack the index of previous data. I am running the bitcoin client with the -reindex parameter and it may take a day or two to complete. I'll test how things go after everything is done.

Thanks

Thanks

**Comment by veryyoung** [comment]
> @samedcildir @nathanddrake Hi, thank you for your replies. My node data was downloaded from the Internet and may lack the index of previous data. I am running the bitcoin client with the -reindex parameter and it may take a day or two to complete. I'll test how things go after everything is done.
> 
> Thanks
> 
> Thanks

Problem solved, thanks for you help!
