### ISSUE TITLE
May I ask when Runes Indexer will officially support

### ISSUE THREAD

**Issue by Meteriox** [bestinslot-xyz/OPI#38]
i have seen there is `runes api` and `runes index` dir in this repo, you guys are working on this. i wonder when you guys will support runes officially or i can use this repo to index runes txs currently.

**Comment by nathanddrake** [comment]
Hi @yibishufange, yes you can use it to index runes now and in the future 👍

**Comment by samedcildir** [comment]
API in the repository is actually added as a reference guide to build API using OPI indexer. It is not a complete API but it has some building blocks which can be extended by adding new endpoints.
Also the event structure of BRC-20 and Runes are very different so the response cannot be in the same structure.

However, you can simply change:
```
    select event_type, outpoint, pkscript, rune_id, amount
                  from runes_events re
                  where block_height = $1
                  order by id asc;
    let res = await query_db(query, [block_height])
    let result = []
    for (const row of res.rows) {
      result.push({
        event_type: event_type_id_to_name[row.event_type],
        outpoint: row.outpoint,
        pkscript: row.pkscript,
        rune_id: row.rune_id,
        amount: row.amount
      })
    }
```
to:
```
    select event_type, outpoint, pkscript, wallet_addr, rune_id, amount
                  from runes_events re
                  where block_height = $1
                  order by id asc;
    let res = await query_db(query, [block_height])
    let result = []
    for (const row of res.rows) {
      result.push({
        event_type: event_type_id_to_name[row.event_type],
        outpoint: row.outpoint,
        pkscript: row.pkscript,
        wallet_addr: row.wallet_addr,
        rune_id: row.rune_id,
        amount: row.amount
      })
    }
```
to include wallet_addr information in the response of this endpoint.
