### ISSUE TITLE
Request for DB Snapshot

### ISSUE THREAD

**Issue by tcrst** [bestinslot-xyz/OPI#48]
Indexing from 0 takes quite a bit of time. Could we maybe make the latest DB snapshot accessible to the public? It would save time for everyone. Thanks

**Comment by samedcildir** [comment]
We actually do have a snapshot function. A new snapshot is taken daily so it should be at max 1 day behind.

You can check the details from [INSTALL.ubuntu.md](https://github.com/bestinslot-xyz/OPI/blob/main/INSTALL.ubuntu.md) at optional restore section. If you're not using linux, you can directly fetch the files using the s3 details in the [restore.py](https://github.com/bestinslot-xyz/OPI/blob/main/modules/restore.py) file or you can run restore.py on download only mode.
