### ISSUE TITLE
main index stopped at block 2862951 (testnet)

### ISSUE THREAD

**Issue by ArthurQiuys** [bestinslot-xyz/OPI#50]
[indexing blocks] ████████████████████████████████████████████░░ 2862950/2970923cmd;2862950;new_block;00000000000000fec443922ee40051c7736fd52dc9fe4f6f81b30029e4b7359c
cmd;2862950;block_start
cmd;2862950;block_end
[indexing blocks] ████████████████████████████████████████████░░ 2862951/2970923
Pause for

**Comment by samedcildir** [comment]
we currently do not support testnet due to bigger than 10 block reorgs. You can use testnet4 instead.
