### ISSUE TITLE
restore.py backups for Testnet?

### ISSUE THREAD

**Issue by bombnp** [bestinslot-xyz/OPI#54]
Hi @samedcildir , thank you for your work.

I see that there is a `restore.py` file for restoring backups (both redb and postgres), but it seems to only work with mainnet? Are there backups for testnet as well, or do I need to start from genesis?

**Comment by samedcildir** [comment]
It did support testnet3 at first, before the difficulty bug is used widely. However currently it gets stuck a lot since the ord version that OPI relies on does not support more than 10 blocks reorgs.

**Comment by bombnp** [comment]
I see. If I decide to run OPI on testnet3 anyways, and problems occur, are those problems recoverable? Or will it be a pain to resolve (from your experience)? Asking for advice.

I'm testing out some brc20 apps and testnet3 is the only option for me right now.

**Comment by samedcildir** [comment]
If a reorg occurs, index.redb will not be able to rollback so you have to start syncing from the beginning. However you can change the rollback height limit parameter in ord and rebuild it

**Comment by bombnp** [comment]
You mean `SAVEPOINT_INTERVAL` and `CHAIN_TIP_DISTANCE` variable? Do I need to change anything else?
https://github.com/bestinslot-xyz/OPI/blob/main/ord/src/index/reorg.rs#L23

**Comment by samedcildir** [comment]
yes, you should also edit https://github.com/bestinslot-xyz/OPI/blob/5b96207e1e84cc23594c41a71d47c1d475288000/modules/brc20_index/brc20_index.py#L680 this line and increase the limit in the query, otherwise brc20_index will stop after a reorg.

**Comment by bombnp** [comment]
Awesome, thank you so much, @samedcildir !
