### ISSUE TITLE
Tag releases with semantic versioning?

### ISSUE THREAD

**Issue by t4t5** [bestinslot-xyz/OPI#8]
It would be nice to have official tagged releases so that users of the library know when breaking changes have been introduced that require rebuilding the database.

Otherwise you might pull the latest changes expecting some minor bug fixes only to be forced to roll all your data back 😬

**Comment by samedcildir** [comment]
Noted 👍
We'll definitely add releases, also we're trying to make rebuild as unnecessary as possible but we've found a bug which would affect sns indexing which will be introduced shortly, so we've decided to push the fix as soon as possible.

We will announce breaking changes in releases from now on.

**Comment by samedcildir** [comment]
I've added a new release tag (v0.3.0) for final commit. Normally in semantic versioning, a Minor version change is backwards compatible, however currently we're not ready for v1.0.0 so I've used minor version update for reindex necessary changes (just like ordinals/ord)
